export const RoutePermissionMap: { [key: string]: string } = {
    'dashboard': 'VIEW_DASHBOARD',
    'customers': 'VIEW_CUSTOMERS',
    'orders': 'VIEW_ORDERS',
    'products': 'VIEW_PRODUCTS',
    'users': 'VIEW_USERS',
    'settings': 'VIEW_SETTINGS',
    'reports': 'VIEW_REPORTS',
    'login': 'VIEW_LOGIN',
    'logout': 'VIEW_LOGOUT',
    'unauthorized': 'VIEW_UNAUTHORIZED',
    'roles-permissions': 'VIEW_ROLES_PERMISSIONS',
    'vip-customers': 'VIEW_VIP_CUSTOMERS',
    'login-attempts': 'VIEW_LOGIN_ATTEMPTS',
    'login-attempts/details': 'VIEW_LOGIN_ATTEMPTS_DETAILS',
    'login-attempts/details/id': 'VIEW_LOGIN_ATTEMPTS_DETAILS_ID',
    'login-attempts/details/id/edit': 'EDIT_LOGIN_ATTEMPTS_DETAILS_ID',
    'login-attempts/details/id/delete': 'DELETE_LOGIN_ATTEMPTS_DETAILS_ID',
    'login-attempts/details/id/view': 'VIEW_LOGIN_ATTEMPTS_DETAILS_ID',
    'product': 'VIEW_PRODUCT',
    'product/create': 'CREATE_PRODUCT',
    'users.create': 'CREATE_USER',
    'admin/products/:id': 'VIEW_PRODUCT_DETAIL',
    'users/roles': 'MANAGE_ROLES',
  };
  